services:
  backend:
    build: ./backend
    ports:
      - "20262:20262"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "20261:80"
    restart: always
