services:
  backend:
    image: ghcr.io/yunuslnk/smart-mudik-2026-backend:main
    ports:
      - "20262:20262"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  frontend:
    image: ghcr.io/yunuslnk/smart-mudik-2026-frontend:main
    ports:
      - "20261:80"
    restart: always
